export const API_ENDPOINTS = {
  AUTH_LOGIN: '/auth/login',
  AUTH_REFRESH: '/auth/refresh',
  AUTH_REGISTER: '/auth/registrar',
  PASSWORD_RESET_REQUEST: '/recuperar-senha/solicitar',
  PASSWORD_RESET_VERIFY: '/recuperar-senha/verificar',
  PASSWORD_RESET_RESET: '/recuperar-senha/redefinir',
  PUBLIC_DASHBOARD: '/public/dashboard',
  DASHBOARD_PUBLICO: '/dashboard/publico',
  DASHBOARD_PESQUISADOR: '/dashboard/pesquisador',
  DASHBOARD_GESTOR: '/dashboard/gestor',
  DASHBOARD_ADMIN: '/dashboard/admin',
  DASHBOARD_RECENTES: '/dashboard/recentes',
  CITIZEN_PROFILE: '/citizen/profile',
  USER_PROFILE_ME: '/usuarios/me',
  USER_PROFILE_CHANGE_PASSWORD: '/usuarios/me/change-password',
  USERS: '/usuarios',
  TREES: '/arvores',
  MAP_TREES: '/map/trees',
  TREE_RECORDS: '/registros',
  APPROVAL_REQUESTS: '/approval-requests',
  APPROVAL_REQUESTS_CREATE_TREE: '/approval-requests/criacao-arvore',
  APPROVAL_REQUESTS_CREATE_RECORD: '/approval-requests/criacao-registro',
  APPROVAL_REQUESTS_EDIT_RECORD: '/approval-requests/edicao-registro',
} as const

export const AUTH_ROUTE_ENDPOINTS = {
  LOGIN: '/api/auth/login',
  REFRESH: '/api/auth/refresh',
  LOGOUT: '/api/auth/logout',
  SESSION: '/api/auth/session',
} as const
