export const APP_ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  PUBLIC_DASHBOARD: '/public',
  CITIZEN_HOME: '/citizen',
  CITIZEN_PROFILE: '/citizen/profile',
  CITIZEN_REPORTS: '/citizen/reports',
  CITIZEN_MAP: '/citizen/map',
  RESEARCHER_HOME: '/researcher',
  RESEARCHER_TREES: '/researcher/trees',
  RESEARCHER_MEASUREMENTS: '/researcher/measurements',
  RESEARCHER_MEASUREMENTS_NEW: '/researcher/measurements/new',
  RESEARCHER_REPORTS: '/researcher/reports',
  RESEARCHER_MAP: '/researcher/map',
  MANAGER_HOME: '/manager',
  MANAGER_APPROVALS: '/manager/approvals',
  MANAGER_USERS: '/manager/users',
  MANAGER_EXPORT: '/manager/export',
} as const
